version: "3"
services:
  web:
    build: "."
    working_dir: /usr/src
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8080:8080"
    command: "npm start"
  storybook:
      build: "."
      working_dir: /usr/src
      environment:
        - NODE_ENV=development
      volumes:
        - ./app:/usr/src/app
      ports:
        - "6006:6006"
      command: "npm run storybook"